spring:
  config:
    import:
      - optional:file:.env-prod.properties
logging:
  level:
    com.rick.backend: DEBUG
    com.rick.db: DEBUG
    com:
      zaxxer:
        hikari:
          ERROR
  file:
    path: log